export enum StockWriteOffReason {
  DAMAGED = 'DAMAGED',
  EXPIRED = 'EXPIRED',
  DEFECTIVE = 'DEFECTIVE',
  CONTAMINATED = 'CONTAMINATED',
  LOST = 'LOST',
  INVENTORY_ERROR = 'INVENTORY_ERROR',
  OTHER = 'OTHER',
}
